// Code generated by MockGen. DO NOT EDIT.
// Source: url_manager.go
//
// Generated by this command:
//
//	mockgen -source=url_manager.go -destination=../storage/mock/mock_user_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/Luclpor/url_shortener.git/internal/model"
	dto "github.com/Luclpor/url_shortener.git/internal/model/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockURLRepository is a mock of URLRepository interface.
type MockURLRepository struct {
	ctrl     *gomock.Controller
	recorder *MockURLRepositoryMockRecorder
	isgomock struct{}
}

// MockURLRepositoryMockRecorder is the mock recorder for MockURLRepository.
type MockURLRepositoryMockRecorder struct {
	mock *MockURLRepository
}

// NewMockURLRepository creates a new mock instance.
func NewMockURLRepository(ctrl *gomock.Controller) *MockURLRepository {
	mock := &MockURLRepository{ctrl: ctrl}
	mock.recorder = &MockURLRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLRepository) EXPECT() *MockURLRepositoryMockRecorder {
	return m.recorder
}

// FindByOriginalURL mocks base method.
func (m *MockURLRepository) FindByOriginalURL(ctx context.Context, longURL string) (*model.ShortenURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOriginalURL", ctx, longURL)
	ret0, _ := ret[0].(*model.ShortenURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOriginalURL indicates an expected call of FindByOriginalURL.
func (mr *MockURLRepositoryMockRecorder) FindByOriginalURL(ctx, longURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOriginalURL", reflect.TypeOf((*MockURLRepository)(nil).FindByOriginalURL), ctx, longURL)
}

// FindByShortURL mocks base method.
func (m *MockURLRepository) FindByShortURL(ctx context.Context, shortURL string) (*model.ShortenURL, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShortURL", ctx, shortURL)
	ret0, _ := ret[0].(*model.ShortenURL)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// FindByShortURL indicates an expected call of FindByShortURL.
func (mr *MockURLRepositoryMockRecorder) FindByShortURL(ctx, shortURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShortURL", reflect.TypeOf((*MockURLRepository)(nil).FindByShortURL), ctx, shortURL)
}

// Save mocks base method.
func (m *MockURLRepository) Save(ctx context.Context, shortURL, fullURL string) (*model.ShortenURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, shortURL, fullURL)
	ret0, _ := ret[0].(*model.ShortenURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockURLRepositoryMockRecorder) Save(ctx, shortURL, fullURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockURLRepository)(nil).Save), ctx, shortURL, fullURL)
}

// SaveBatch mocks base method.
func (m *MockURLRepository) SaveBatch(ctx context.Context, dtos []dto.URLDto) ([]model.ShortenURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatch", ctx, dtos)
	ret0, _ := ret[0].([]model.ShortenURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveBatch indicates an expected call of SaveBatch.
func (mr *MockURLRepositoryMockRecorder) SaveBatch(ctx, dtos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatch", reflect.TypeOf((*MockURLRepository)(nil).SaveBatch), ctx, dtos)
}
