package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"text/template"
)

const (
	generatedFileName = "reset.gen.go"
	resetComment      = "generate:reset"
)

const resetFileTemplate = `// Code generated by cmd/reset; DO NOT EDIT.

package {{ .PackageName }}

{{ range .Methods -}}
func (r *{{ .ReceiverType }}) Reset() {
	if r == nil {
		return
	}
{{ if .Body }}
{{ .Body }}{{ end -}}
}

{{ end -}}`

var generatedFileTemplate = template.Must(template.New("reset-file").Parse(resetFileTemplate))

type packageInfo struct {
	dir     string
	name    string
	fset    *token.FileSet
	structs []structInfo
}

type structInfo struct {
	name       string
	typeParams []string
	fields     []*ast.Field
}

func main() {
	flag.Parse()

	root := "."
	if flag.NArg() > 0 {
		root = flag.Arg(0)
	}

	if err := run(root); err != nil {
		log.Fatal(err)
	}
}

func run(root string) error {
	packages, err := scanPackages(root)
	if err != nil {
		return err
	}

	for _, pkg := range packages {
		if len(pkg.structs) == 0 {
			continue
		}
		if err := writeResetFile(pkg); err != nil {
			return err
		}
	}

	return nil
}

func scanPackages(root string) ([]packageInfo, error) {
	root, err := filepath.Abs(root)
	if err != nil {
		return nil, err
	}

	var packages []packageInfo
	err = filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if !entry.IsDir() {
			return nil
		}
		if shouldSkipDir(root, path, entry.Name()) {
			return filepath.SkipDir
		}

		pkg, err := parsePackage(path)
		if err != nil {
			return err
		}
		if pkg != nil {
			packages = append(packages, *pkg)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	slices.SortFunc(packages, func(a, b packageInfo) int {
		return strings.Compare(a.dir, b.dir)
	})
	return packages, nil
}

func shouldSkipDir(root, path, name string) bool {
	if path == root {
		return false
	}
	if name == "vendor" || name == "node_modules" || name == "testdata" {
		return true
	}
	return strings.HasPrefix(name, ".")
}

func parsePackage(dir string) (*packageInfo, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, sourceFileFilter, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	if len(pkgs) == 0 {
		return nil, nil
	}
	if len(pkgs) > 1 {
		return nil, fmt.Errorf("multiple packages in %s", dir)
	}

	for name, pkg := range pkgs {
		info := packageInfo{
			dir:  dir,
			name: name,
			fset: fset,
		}

		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}
				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok || typeSpec.Assign.IsValid() {
						continue
					}
					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok || !hasResetComment(genDecl.Doc) && !hasResetComment(typeSpec.Doc) {
						continue
					}

					info.structs = append(info.structs, structInfo{
						name:       typeSpec.Name.Name,
						typeParams: typeParamNames(typeSpec.TypeParams),
						fields:     structType.Fields.List,
					})
				}
			}
		}

		return &info, nil
	}

	return nil, nil
}

func sourceFileFilter(info fs.FileInfo) bool {
	name := info.Name()
	return strings.HasSuffix(name, ".go") &&
		!strings.HasSuffix(name, "_test.go") &&
		name != generatedFileName
}

func hasResetComment(group *ast.CommentGroup) bool {
	if group == nil {
		return false
	}
	for _, comment := range group.List {
		text := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
		if text == resetComment {
			return true
		}
	}
	return false
}

func typeParamNames(params *ast.FieldList) []string {
	if params == nil {
		return nil
	}

	var names []string
	for _, field := range params.List {
		for _, name := range field.Names {
			names = append(names, name.Name)
		}
	}
	return names
}

func writeResetFile(pkg packageInfo) error {
	var buf bytes.Buffer
	if err := generatedFileTemplate.Execute(&buf, resetFileData(pkg)); err != nil {
		return fmt.Errorf("execute reset template for %s: %w", pkg.dir, err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated reset code for %s: %w\n%s", pkg.dir, err, buf.String())
	}

	return os.WriteFile(filepath.Join(pkg.dir, generatedFileName), formatted, 0644)
}

type resetFileTemplateData struct {
	PackageName string
	Methods     []resetMethodTemplateData
}

type resetMethodTemplateData struct {
	ReceiverType string
	Body         string
}

func resetFileData(pkg packageInfo) resetFileTemplateData {
	methods := make([]resetMethodTemplateData, 0, len(pkg.structs))
	for _, st := range pkg.structs {
		g := generator{fset: pkg.fset}
		methods = append(methods, g.resetMethodData(st))
	}

	return resetFileTemplateData{
		PackageName: pkg.name,
		Methods:     methods,
	}
}

type generator struct {
	fset      *token.FileSet
	zeroID    int
	indexID   int
	indent    int
	typeCache map[ast.Expr]string
}

func (g *generator) resetMethodData(st structInfo) resetMethodTemplateData {
	receiverType := st.name
	if len(st.typeParams) > 0 {
		receiverType += "[" + strings.Join(st.typeParams, ", ") + "]"
	}

	var buf bytes.Buffer
	g.indent = 1
	for _, field := range st.fields {
		for _, name := range fieldNames(field) {
			g.writeReset(&buf, "r."+name, field.Type)
		}
	}

	return resetMethodTemplateData{
		ReceiverType: receiverType,
		Body:         buf.String(),
	}
}

func (g *generator) writeReset(buf *bytes.Buffer, target string, typ ast.Expr) {
	switch t := typ.(type) {
	case *ast.Ident:
		if zero, ok := primitiveZero(t.Name); ok {
			g.writeLine(buf, "%s = %s", target, zero)
			return
		}
		g.writeResettableOrZero(buf, target, typ)
	case *ast.SelectorExpr, *ast.IndexExpr, *ast.IndexListExpr:
		g.writeResettableOrZero(buf, target, typ)
	case *ast.ArrayType:
		if t.Len == nil {
			g.writeLine(buf, "%s = (%s)[:0]", target, target)
			return
		}
		index := g.nextIndex()
		g.writeLine(buf, "for %s := range %s {", index, target)
		g.indent++
		g.writeReset(buf, fmt.Sprintf("%s[%s]", target, index), t.Elt)
		g.indent--
		g.writeLine(buf, "}")
	case *ast.MapType:
		g.writeLine(buf, "clear(%s)", target)
	case *ast.StarExpr:
		g.writeLine(buf, "if %s != nil {", target)
		g.indent++
		g.writeReset(buf, deref(target), t.X)
		g.indent--
		g.writeLine(buf, "}")
	case *ast.StructType:
		for _, field := range t.Fields.List {
			for _, name := range fieldNames(field) {
				g.writeReset(buf, selector(target, name), field.Type)
			}
		}
	case *ast.InterfaceType:
		g.writeLine(buf, "if resetter, ok := %s.(interface{ Reset() }); ok {", target)
		g.indent++
		g.writeLine(buf, "resetter.Reset()")
		g.indent--
		g.writeLine(buf, "} else {")
		g.indent++
		g.writeLine(buf, "%s = nil", target)
		g.indent--
		g.writeLine(buf, "}")
	case *ast.ChanType, *ast.FuncType:
		g.writeLine(buf, "%s = nil", target)
	default:
		g.writeZeroAssign(buf, target, typ)
	}
}

func (g *generator) writeResettableOrZero(buf *bytes.Buffer, target string, typ ast.Expr) {
	g.writeLine(buf, "if resetter, ok := any(&(%s)).(interface{ Reset() }); ok {", target)
	g.indent++
	g.writeLine(buf, "resetter.Reset()")
	g.indent--
	g.writeLine(buf, "} else {")
	g.indent++
	g.writeZeroAssign(buf, target, typ)
	g.indent--
	g.writeLine(buf, "}")
}

func (g *generator) writeZeroAssign(buf *bytes.Buffer, target string, typ ast.Expr) {
	zeroName := g.nextZero()
	g.writeLine(buf, "var %s %s", zeroName, g.exprString(typ))
	g.writeLine(buf, "%s = %s", target, zeroName)
}

func (g *generator) writeLine(buf *bytes.Buffer, format string, args ...any) {
	for range g.indent {
		buf.WriteByte('\t')
	}
	fmt.Fprintf(buf, format, args...)
	buf.WriteByte('\n')
}

func (g *generator) nextZero() string {
	name := fmt.Sprintf("zero%d", g.zeroID)
	g.zeroID++
	return name
}

func (g *generator) nextIndex() string {
	name := fmt.Sprintf("i%d", g.indexID)
	g.indexID++
	return name
}

func (g *generator) exprString(expr ast.Expr) string {
	if g.typeCache == nil {
		g.typeCache = make(map[ast.Expr]string)
	}
	if cached, ok := g.typeCache[expr]; ok {
		return cached
	}

	var buf bytes.Buffer
	if err := printer.Fprint(&buf, g.fset, expr); err != nil {
		return "any"
	}
	text := buf.String()
	g.typeCache[expr] = text
	return text
}

func fieldNames(field *ast.Field) []string {
	if len(field.Names) > 0 {
		names := make([]string, 0, len(field.Names))
		for _, name := range field.Names {
			if name.Name != "_" {
				names = append(names, name.Name)
			}
		}
		return names
	}

	name := embeddedFieldName(field.Type)
	if name == "" || name == "_" {
		return nil
	}
	return []string{name}
}

func embeddedFieldName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return t.Sel.Name
	case *ast.StarExpr:
		return embeddedFieldName(t.X)
	case *ast.IndexExpr:
		return embeddedFieldName(t.X)
	case *ast.IndexListExpr:
		return embeddedFieldName(t.X)
	default:
		return ""
	}
}

func primitiveZero(name string) (string, bool) {
	switch name {
	case "bool":
		return "false", true
	case "string":
		return `""`, true
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"uintptr", "byte", "rune",
		"float32", "float64", "complex64", "complex128":
		return "0", true
	default:
		return "", false
	}
}

func deref(expr string) string {
	return "*(" + expr + ")"
}

func selector(expr, field string) string {
	return "(" + expr + ")." + field
}
